version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_prod
    image: api_rust:v1
    user: root
    command: sh -c "cargo run"
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/opt/project
      - ~/.cargo:/root/.cargo
    expose:
      - 80
      - 443
      - 8000
    depends_on:
      - db

  api_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: api_rust:dev
    user: root
    command: sh -c "cargo run"
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/opt/project
      - ~/.cargo:/root/.cargo
    expose:
      - 80
      - 443
      - 8000
    depends_on:
      - db

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: api_rust:test
    user: root
    command: sh -c "cargo test"
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    env_file:
      - ./.env_test
    volumes:
      - .:/opt/project
      - ~/.cargo:/root/.cargo
    expose:
      - 80
      - 443
      - 8000
    depends_on:
      - db_test

  db:
    build:
      context:
        db
      dockerfile: Dockerfile_pg
    user: root
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tests
      - PGDATA=/var/lib/postgresql/data/pgdata

  db_test:
    build:
      context:
        db
      dockerfile: Dockerfile_pg_test
    user: root
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tests
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  cargo: {}
  pgdata: {}