FROM rustlang/rust:nightly as build

# create a new empty shell project
RUN USER=root cargo new --bin api_rust
WORKDIR /api_rust
COPY . .

RUN cargo install diesel_cli --no-default-features --features postgres
RUN sh -c "entrypoint.sh"

RUN cargo build --release

# our final base
FROM debian:buster-slimS

RUN apt-get update && apt-get -y install libpq5

# copy the build artifact from the build stage
COPY --from=build /api_rust/target/release/api_rust .
COPY ./migrations ./migrations
COPY ./.env ./.env

# set the startup command to run your binary
CMD ["./api_rust"]







